# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alarm.proto',
  package='com.vision.models.alarm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61larm.proto\x12\x17\x63om.vision.models.alarm\"\x97\x01\n\x05\x41larm\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12-\n\x05level\x18\x04 \x01(\x0e\x32\x1e.com.vision.models.alarm.Level\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x0c\n\x04meta\x18\x07 \x01(\t\"R\n\x0b\x41\x63knowledge\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63knowledge\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t*m\n\x05Level\x12\x11\n\rLEVEL_UNKNOWN\x10\x00\x12\x0e\n\nLEVEL_WARN\x10\x01\x12\x12\n\x0eLEVEL_CRITICAL\x10\x02\x12\x0f\n\x0bLEVEL_FATAL\x10\x03\x12\x0c\n\x08LEVEL_OK\x10\x04\x12\x0e\n\nLEVEL_INFO\x10\x05\x62\x06proto3')
)

_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='com.vision.models.alarm.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEVEL_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_WARN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_CRITICAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_FATAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_OK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL_INFO', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=278,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_LEVEL)

Level = enum_type_wrapper.EnumTypeWrapper(_LEVEL)
LEVEL_UNKNOWN = 0
LEVEL_WARN = 1
LEVEL_CRITICAL = 2
LEVEL_FATAL = 3
LEVEL_OK = 4
LEVEL_INFO = 5



_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='com.vision.models.alarm.Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.vision.models.alarm.Alarm.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.vision.models.alarm.Alarm.stream_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='com.vision.models.alarm.Alarm.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='com.vision.models.alarm.Alarm.level', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.vision.models.alarm.Alarm.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.vision.models.alarm.Alarm.message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='com.vision.models.alarm.Alarm.meta', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=192,
)


_ACKNOWLEDGE = _descriptor.Descriptor(
  name='Acknowledge',
  full_name='com.vision.models.alarm.Acknowledge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.vision.models.alarm.Acknowledge.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.vision.models.alarm.Acknowledge.stream_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acknowledge', full_name='com.vision.models.alarm.Acknowledge.acknowledge', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.vision.models.alarm.Acknowledge.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=276,
)

_ALARM.fields_by_name['level'].enum_type = _LEVEL
DESCRIPTOR.message_types_by_name['Alarm'] = _ALARM
DESCRIPTOR.message_types_by_name['Acknowledge'] = _ACKNOWLEDGE
DESCRIPTOR.enum_types_by_name['Level'] = _LEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Alarm = _reflection.GeneratedProtocolMessageType('Alarm', (_message.Message,), dict(
  DESCRIPTOR = _ALARM,
  __module__ = 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:com.vision.models.alarm.Alarm)
  ))
_sym_db.RegisterMessage(Alarm)

Acknowledge = _reflection.GeneratedProtocolMessageType('Acknowledge', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGE,
  __module__ = 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:com.vision.models.alarm.Acknowledge)
  ))
_sym_db.RegisterMessage(Acknowledge)


# @@protoc_insertion_point(module_scope)
